### ISSUE TITLE
GetMarketingChannelRules() - 'matches' column returning same value for each rule component

### ISSUE THREAD

**Issue by wmcraver** [randyzwitch/RSiteCatalyst#180]
When I run the GetMarketingChannelRules() on several report suites, I'm finding that the "matches" column is not reporting accurately.

For Instance, I have a rule for a particular channel that looks at the query string parameter to see if it _starts with_ "ps" and _contains_ "google".  When running GetMarketingChannelRules("myreportsuite"), it returns the rule printed out on the two lines as expected, but the "matches" column lists the "ps" value for both rows.

**Comment by randyzwitch** [comment]
Thanks for reporting this. I just tried it and it does seem like a bug.

**Comment by randyzwitch** [comment]
Thanks for sending me your demo file @wmcraver!  I believe I've fixed the issue with the newest commit I pushed to master.

If you could test, that would be fantastic (especially for multiple report suites at the same time if you can):

```R
library(devtools)
install_github("randyzwitch/RSiteCatalyst")
```

**Comment by wmcraver** [comment]
I updated (fabc9945) and tested again.  I'm still seeing the "matches" column return duplicate values for rules with multiple conditions.

**Comment by randyzwitch** [comment]
Ha! So I misunderstood the original problem, found a different bug in this function, and then fixed that :)

In terms of duplicate rows, are you sure this isn't actually part of your marketing rules definitions? The way I'm parsing the JSON response from the Adobe API, there really shouldn't be a way for me to duplicate rows. For example, from the default marketing channels setup in my development suite:

<img width="1374" alt="screen shot 2017-04-05 at 9 24 30 am" src="https://cloud.githubusercontent.com/assets/2762787/24707485/c4d85b28-19e1-11e7-863b-0df8d0b7e493.png">

**Comment by wmcraver** [comment]
They're definitely not configured identically.  Attached is how one particular channel is configured in Adobe and how they being returned from the function.  The _matches_ column shows"BL" for all 5 rows in the data frame.

![marketingchannelruleexample](https://cloud.githubusercontent.com/assets/622307/24713962/f69a8f7e-19db-11e7-9161-4b4a6187f7fc.PNG)
![marketingchannelruleexample-r](https://cloud.githubusercontent.com/assets/622307/24713968/f94cb670-19db-11e7-9ef5-ccce76a8ebca.PNG)

**Comment by randyzwitch** [comment]
Interesting. The rule_id values indicate that the rows are nominally different, but the matches column is duplicated. I'll take a look at the code again, I'm not sure what I could do to cause something like that!

**Comment by randyzwitch** [comment]
Okay, managed to set up a new MC Rules to mimic yours and I get the same behavior:

<img width="1382" alt="screen shot 2017-04-05 at 2 34 21 pm" src="https://cloud.githubusercontent.com/assets/2762787/24721050/10621fc2-1a0d-11e7-9fc2-439435c6253a.png">

**Comment by randyzwitch** [comment]
Ok, the latest master should have the fix! Another horrible parser hack, but I replicated the error showing a repeated value, then got the parser to return the correct matches values.

Let me know if you still have this problem, and if not, then this fix will make it into the next RSiteCatalyst release.

**Comment by wmcraver** [comment]
That fixed it!  Thank you so much for your work on this one!
